### ISSUE TITLE
Set Private Key to Environment Variables

### ISSUE THREAD

**Issue by idea404** [dutterbutter/nft-paymaster-dapp#1]
Tests currently hardcode the private key for the testnet account. Not only is this bad practice but considering this is an example, it should show developers how to deal with this regularly. 

https://github.com/dutterbutter/nft-paymaster-dapp/blob/c9ee98f34d42952c3ae7ee825355981940dfe3ec/zksync/test/main.test.ts#L7

I suggest replacing the above with for example:

```ts
const PRIVATE_KEY: any = process.env.PRIVATE_KEY;
if (!PRIVATE_KEY) {
    throw ... 
};
```

and include the private key in the repo secrets that get loaded whenever a GitHub Action runs for example.

**Comment by dutterbutter** [comment]
Yes I agree, this was bootstrapped with zksync-cli which pulls in the following template: https://github.com/matter-labs/zksync-hardhat-template/blob/main/test/main.test.ts

Please raise this issue there as well.
